### ISSUE TITLE
Bug in the keras example script

### ISSUE THREAD

**Issue by mjsML** [onnx/onnx-docker#18]
This line should be onnx_model = onnxmltools.convert_keras(keras_model) instead of onnx_model = onnxmltools.convert_keras(model)
[https://github.com/onnx/onnx-docker/blob/acc63660e8143b7f9834aaf0e85551e3f0e2e9e5/onnx-ecosystem/converter_scripts/keras_onnx.ipynb#L36](link)

**Comment by EmmaNingMS** [comment]
@vinitra could you help take a look?

**Comment by vinitra** [comment]
Looks like the fix in #22 addresses this. Thanks!
