### ISSUE TITLE
Bug in onnx-docker/onnx-ecosystem/converter_scripts/lightgbm_onnx.ipynb

### ISSUE THREAD

**Issue by Joldnine** [onnx/onnx-docker#27]
When I execute the playbook, it raises ValueError: 
```
Initial types are required. See usage of convert(...) in onnxmltools.convert.lightgbm.convert for details
```
My versions:
onnxmltools==1.6.0
The reason may be the old API compatibility issue. I notice there are many changes in latest onnxmltools version.

**Comment by vinitra** [comment]
Addressed with https://github.com/onnx/onnx-docker/commit/b5aeafc7e15757bfbffcd830dea4b56969ea91fc .

Thanks for the feedback!
