### ISSUE TITLE
Cannot start container

### ISSUE THREAD

**Issue by zldrobit** [onnx/onnx-docker#30]
I ran the following command:
`docker run --rm -it --name onnx --gpus all  onnx/onnx-ecosystem /bin/bash`
which complainted:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: file creation failed: /var/lib/docker/overlay2/97a44c71fcaa06bb83388796dbcd0c03943a442693da8a6acf0dfd1f3889e9e7/merged/usr/bin/nvidia-smi: file exists\\\\n\\\"\"": unknown.`

https://github.com/NVIDIA/nvidia-docker/issues/825 saids that the reason is that nvidia driver e.g. nvidia-smi is in the image.
I have installed nvidia driver on the host.
Is it intended to not install nvidia driver on the host when using onnx-runtime container?

**Comment by vinitra** [comment]
Hello @zldrobit! No, the onnx-ecosystem image is meant to be a CPU image (although the initial dockerfiles can be modified to include a GPU offering without changing too much code). You can find onnxruntime GPU images here: https://github.com/microsoft/onnxruntime/tree/master/dockerfiles#cuda
