### ISSUE TITLE
Cannot allocate buffer larger than kint32max for StringOutputStream.

### ISSUE THREAD

**Issue by toyow** [onnx/onnx-docker#32]
when I run caffe_coreml_onnx.ipynb with  VGG_ILSVRC_16_layers.caffemodel,this problem occurs.

`[libprotobuf ERROR google/protobuf/io/zero_copy_stream_impl_lite.cc:155] Cannot allocate buffer larger than kint32max for StringOutputStream.`

**Comment by vinitra** [comment]
Unfortunately, we cannot replicate this without a repro environment. Can you provide the original model? Alternatively, you might find the VGG 16 model in the onnx model zoo useful for your purpose: https://github.com/onnx/models/tree/master/vision/classification/vgg

**Comment by prasanthpul** [comment]
Closing this old issue. Please reopen with the requested info if needed
