### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by givens** [onnx/onnx-docker#34]
I am new to docker and onnx.  I am converting from Caffe to another format.  I read this line:

"Navigate to the converter_scripts folder in the container and edit the appropriate notebook to convert your model to ONNX, or test the accuracy of the conversion using ONNX Runtime."

I do not know how to navigate to the converter scripts.  Is there a link or small contribution that could be made explaining this point?  There could be more explanation in general to this point.

**Comment by vinitra** [comment]
Thank you for your suggestion. We are continually working on improving documentation.

The "navigate" is in reference to the Jupyter notebook UI by clicking on the folder names. Did you launch the Jupyter environment with the following command successfully?

docker run -p 8888:8888 onnx/onnx-ecosystem

After that, you'll want to navigate to the appropriate URL as mentioned in step 4 of [the instructions](https://github.com/onnx/onnx-docker/tree/master/onnx-ecosystem): 

> Navigate to the url that the Jupyter Notebook is running on and use the provided token in the console. Should be in the form: http://127.0.0.1:8888/?token=RANDOMSTRINGHERE
