### ISSUE TITLE
No performance improvement using fp16 model?

### ISSUE THREAD

**Issue by zealerww** [onnx/onnx-docker#35]
I follow https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/converter_scripts/float32_float16_onnx.ipynb to covert a resnet50 model to fp16，but I got no performance improvement when I using onnxruntime to test.
How can I get performance improvement?

**Comment by ebarsoum** [comment]
Can you provide more details? Which GPU did you run it on? Version of CUDA and cuDNN?

**Comment by zealerww** [comment]
@ebarsoum 
I test fp16 and int8 model in cpu (Intel(R) Xeon(R) CPU E5-2650 v4)
f16 model converted using  https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/converter_scripts/float32_float16_onnx.ipynb 
int8 model converted using https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization

* fp32: time 1s; cpu usage 600%
* fp16: time 1s; cpu usage 600%
* int8: time 4s; cpu usage 100%

It seems that fp16 and int8 model has no improvement in cpu.

**Comment by zealerww** [comment]
I got answer in https://github.com/microsoft/onnxruntime/issues/2871. Thanks.
