### ISSUE TITLE
Wrong python3 package specification in onnx-ecosystem Dockerfile

### ISSUE THREAD

**Issue by shaharv** [onnx/onnx-docker#43]
**Problem description:**

- The python3 package name argument to `apt` contains a typo: `python 3.6` - notice the space:
https://github.com/onnx/onnx-docker/blob/b231ce7a6113ea4d725458bc4d2b4ae8168348ed/onnx-ecosystem/Dockerfile#L9

- As a result, `python` 2.7 is installed. Python 3 (3.5) is being pulled in by `python3-dev`.
- Worse, `3.6` is being interpreted as a wildcard matching 1301 packages, most likely unintended and causing image bloat.

**Proposed fix:**

- Updating the base image to `ubuntu:18.04`, the latest LTS, would solve the issue, since python 3.6 is the default python version (currently `3.6.9-1~18.04`) - assuming Python 3.6 is required. Ubuntu 16.04 provides only Python 3.5.
- For being explicit about 3.6, `python3-dev` could be replaced with `python3.6-dev`, too.

**Comment by vinitra** [comment]
Thanks for the suggestions!
